### ISSUE TITLE
failed to build image "adamrehn/ue4-build-prerequisites:1909"

### ISSUE THREAD

**Issue by stone002** [adamrehn/ue4-docker#123] opened 2020-12-24 09:07 UTC
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.75 (latest available version is 0.0.75)
Operating system:           Windows 10 Pro Version 1909 (OS Build 18362.1016)
Docker daemon version:      20.10.0
NVIDIA Docker supported:    No
Maximum image size:         600GB
Available disk space:       1.91 TiB
Total system memory:        31.94 GiB physical, 52.94 GiB virtual
Number of processors:       6 physical, 12 logical
```

Problem output:
```
C:\Users\Admin>ue4-docker build 4.24.3  --exclude debug
[ue4-docker build] COMMAND-LINE INVOCATION:
[ue4-docker build] ['ue4-docker', '4.24.3', '--exclude', 'debug']

[ue4-docker build] UNREAL ENGINE VERSION SETTINGS:
[ue4-docker build] Custom build:  No
[ue4-docker build] Release:       4.24.3
[ue4-docker build] Repository:    https://github.com/EpicGames/UnrealEngine.git
[ue4-docker build] Branch/tag:    4.24.3-release

[ue4-docker build] WINDOWS CONTAINER SETTINGS
[ue4-docker build] Isolation mode:               process
[ue4-docker build] Base OS image tag:            1909 (host OS is Windows 10 version 1909)
[ue4-docker build] Memory limit:                 No limit
[ue4-docker build] Detected max image size:      600GB
[ue4-docker build] Directory to copy DLLs from:  C:\windows\System32

[ue4-docker build] GENERAL SETTINGS
[ue4-docker build] Excluding the following Engine components:
[ue4-docker build] - Debug symbols

Retrieving the Git credentials that will be used to clone the UE4 repo
Using username specified via `-username` command-line argument.
Using password specified via `-password` command-line argument.


[ue4-docker build] Building image "adamrehn/ue4-build-prerequisites:1909"...
Sending build context to Docker daemon   2.05MB
Step 1/27 : ARG BASEIMAGE
Step 2/27 : FROM ${BASEIMAGE} AS dlls
 ---> e84d4c06d7bd
Step 3/27 : SHELL ["cmd", "/S", "/C"]
 ---> Using cache
 ---> 1ed5cb5c33d1
Step 4/27 : LABEL com.adamrehn.ue4-docker.sentinel="1"
 ---> Using cache
 ---> bc17840534fa
Step 5/27 : RUN mkdir C:\GatheredDlls && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> 84a229bb9e9f
Step 6/27 : RUN powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> 2411462b5180
Step 7/27 : RUN choco install -y 7zip curl && choco install -y python --version=3.7.5 && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> 0f292508f5e0
Step 8/27 : COPY *.dll C:\GatheredDlls\
 ---> Using cache
 ---> 6903f83a3594
Step 9/27 : ARG HOST_VERSION
 ---> Using cache
 ---> bf0e7130462a
Step 10/27 : RUN pip install pywin32 && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> 0bcd439df265
Step 11/27 : COPY copy.py verify-host-dlls.py C:\
 ---> Using cache
 ---> 2862754f4946
Step 12/27 : RUN C:\copy.py "C:\GatheredDlls\*.dll" C:\Windows\System32\ && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> 5257ce63bb41
Step 13/27 : RUN python C:\verify-host-dlls.py %HOST_VERSION% C:\GatheredDlls && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> 35194f4685ab
Step 14/27 : RUN curl --progress -L "https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe" --output %TEMP%\directx_redist.exe && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> 8d3da850f849
Step 15/27 : RUN start /wait %TEMP%\directx_redist.exe /Q /T:%TEMP% &&  expand %TEMP%\APR2007_xinput_x64.cab -F:xinput1_3.dll C:\GatheredDlls\ &&       expand %TEMP%\Jun2010_D3DCompiler_43_x64.cab -F:D3DCompiler_43.dll C:\GatheredDlls\ &&  expand %TEMP%\Feb2010_X3DAudio_x64.cab -F:X3DAudio1_7.dll C:\GatheredDlls\ &&  expand %TEMP%\Jun2010_XAudio_x64.cab -F:XAPOFX1_5.dll C:\GatheredDlls\ &&        expand %TEMP%\Jun2010_XAudio_x64.cab -F:XAudio2_7.dll C:\GatheredDlls\ && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> 7ef8c0baa027
Step 16/27 : RUN curl --progress -L "https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-runtime-components.zip?u=" --output %TEMP%\vulkan-runtime-components.zip && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> a7463055d711
Step 17/27 : RUN 7z e %TEMP%\vulkan-runtime-components.zip -oC:\GatheredDlls -y "*\x64\vulkan-1.dll" && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> 0b3093fedcd9
Step 18/27 : RUN choco install -y windows-sdk-10-version-2004-windbg && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Running in 60ea1c947aa5
Chocolatey v0.10.15
Installing the following packages:
windows-sdk-10-version-2004-windbg
By installing you accept licenses for the packages.
Progress: Downloading windows-sdk-10-version-2004-windbg 10.0.19041.0... 100%

windows-sdk-10-version-2004-windbg v10.0.19041.0 [Approved]
windows-sdk-10-version-2004-windbg package files install completed. Performing other installation steps.
Downloading windows-sdk-10-version-2004-windbg
  from 'https://download.microsoft.com/download/1/c/3/1c3d5161-d9e9-4e4b-9b43-b70fe8be268c/windowssdk/winsdksetup.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\windows-sdk-10-version-2004-windbg\10.0.19041.0\winsdksetup.exe (1.29 MB).
Download of winsdksetup.exe (1.29 MB) completed.
Hashes match.
Installing windows-sdk-10-version-2004-windbg...
ERROR: Running ["C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\windows-sdk-10-version-2004-windbg\10.0.19041.0\winsdksetup.exe" /Features OptionId.WindowsDesktopDebuggers /Quiet /NoRestart /Log "C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\windows-sdk-10-version-2004-windbg_d753d717-80a5-444f-a572-1b40a887defe.log" ] was not successful. Exit code was '15605'. See log for possible error messages.
The install of windows-sdk-10-version-2004-windbg was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\windows-sdk-10-version-2004-windbg\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - windows-sdk-10-version-2004-windbg (exited 15605) - Error while running 'C:\ProgramData\chocolatey\lib\windows-sdk-10-version-2004-windbg\tools\chocolateyinstall.ps1'.
 See log for details.
The command 'cmd /S /C choco install -y windows-sdk-10-version-2004-windbg && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.' returned a non-zero code: 15605
[ue4-docker build] Error: failed to build image "adamrehn/ue4-build-prerequisites:1909".
```
Error log message:
```
2020-12-24 10:10:04,677 31152 [DEBUG] - Downloading https://download.microsoft.c
om/download/1/c/3/1c3d5161-d9e9-4e4b-9b43-b70fe8be268c/windowssdk/winsdksetup.ex
e to C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\windows-sdk-1
0-version-2004-windbg\10.0.19041.0\winsdksetup.exe
2020-12-24 10:10:05,012 31152 [INFO ] -
2020-12-24 10:10:05,013 31152 [INFO ] - Download of winsdksetup.exe (1.29 MB) co
mpleted.                       Local\Temp\chocolatey\windows-sdk-10-version-2004
-windbg\10.0.19041.0\winsdksetup.exe'.
2020-12-24 10:10:08,090 31152 [DEBUG] - Running Get-ChecksumValid -file 'C:\User
s\ContainerAdministrator\AppData\Local\Temp\chocolatey\windows-sdk-10-version-20
04-windbg\10.0.19041.0\winsdksetup.exe' -checksum 'd53f651370f87484b78622e30dfb1
a41920b501e4041035771c0d785561f47d5' -checksumType 'sha256' -originalUrl 'https:
//download.microsoft.com/download/1/c/3/1c3d5161-d9e9-4e4b-9b43-b70fe8be268c/win
dowssdk/winsdksetup.exe'
2020-12-24 10:10:08,094 31152 [DEBUG] - checksum.exe found at 'C:\ProgramData\ch
ocolatey\helpers\..\tools\checksum.exe'
2020-12-24 10:10:08,095 31152 [DEBUG] - Executing command ['C:\ProgramData\choco
latey\helpers\..\tools\checksum.exe' -c="d53f651370f87484b78622e30dfb1a41920b501
e4041035771c0d785561f47d5" -t="sha256" -f="C:\Users\ContainerAdministrator\AppDa
ta\Local\Temp\chocolatey\windows-sdk-10-version-2004-windbg\10.0.19041.0\winsdks
etup.exe"]
2020-12-24 10:10:08,167 31152 [DEBUG] - Command ['C:\ProgramData\chocolatey\help
ers\..\tools\checksum.exe' -c="d53f651370f87484b78622e30dfb1a41920b501e404103577
1c0d785561f47d5" -t="sha256" -f="C:\Users\ContainerAdministrator\AppData\Local\T
emp\chocolatey\windows-sdk-10-version-2004-windbg\10.0.19041.0\winsdksetup.exe"]
 exited with '0'.
2020-12-24 10:10:08,180 31152 [DEBUG] - Running Install-ChocolateyInstallPackage
 -packageName 'windows-sdk-10-version-2004-windbg' -fileType 'EXE' -silentArgs '
/Features OptionId.WindowsDesktopDebuggers /Quiet /NoRestart /Log "C:\Users\Cont
ainerAdministrator\AppData\Local\Temp\chocolatey\windows-sdk-10-version-2004-win
dbg_91c1f58a-b438-4dfc-8b39-dc1759426e06.log"' -file 'C:\Users\ContainerAdminist
rator\AppData\Local\Temp\chocolatey\windows-sdk-10-version-2004-windbg\10.0.1904
1.0\winsdksetup.exe' -validExitCodes '0 3010' -useOnlyPackageSilentArguments 'Fa
lse'
2020-12-24 10:10:08,181 31152 [DEBUG] - Running Get-ProcessorBits -compare '32'
2020-12-24 10:10:08,183 31152 [INFO ] - Installing windows-sdk-10-version-2004-w
indbg...
2020-12-24 10:10:08,197 31152 [DEBUG] - Ensuring 'C:\Users\ContainerAdministrato
r\AppData\Local\Temp\chocolatey' exists
2020-12-24 10:10:08,214 31152 [DEBUG] - Running Start-ChocolateyProcessAsAdmin -
validExitCodes '0 3010' -workingDirectory 'C:\Users\ContainerAdministrator\AppDa
ta\Local\Temp\chocolatey\windows-sdk-10-version-2004-windbg\10.0.19041.0' -state
ments '/Features OptionId.WindowsDesktopDebuggers /Quiet /NoRestart /Loag "C:\Use
rs\ContainerAdministrator\AppData\Local\Temp\chocolatey\windows-sdk-10-version-2
004-windbg_91c1f58a-b438-4dfc-8b39-dc1759426e06.log" ' -exeToRun 'C:\Users\Conta
inerAdministrator\AppData\Local\Temp\chocolatey\windows-sdk-10-version-2004-wind
bg\10.0.19041.0\winsdksetup.exe'
2020-12-24 10:10:08,215 31152 [DEBUG] - Unable to use current location for Worki
ng Directory. Using Cache Location instead.
2020-12-24 10:10:08,228 31152 [DEBUG] - Test-ProcessAdminRights: returning True
2020-12-24 10:10:08,233 31152 [DEBUG] - Elevating permissions and running ["C:\U
sers\ContainerAdministrator\AppData\Local\Temp\chocolatey\windows-sdk-10-version
-2004-windbg\10.0.19041.0\winsdksetup.exe" /Features OptionId.WindowsDesktopDebu
ggers /Quiet /NoRestart /Log "C:\Users\ContainerAdministrator\AppData\Local\Temp
\chocolatey\windows-sdk-10-version-2004-windbg_91c1f58a-b438-4dfc-8b39-dc1759426
e06.log" ]. This may take a while, depending on the statements.
2020-12-24 10:12:58,911 31152 [DEBUG] - Command ["C:\Users\ContainerAdministrato
r\AppData\Local\Temp\chocolatey\windows-sdk-10-version-2004-windbg\10.0.19041.0\
winsdksetup.exe" /Features OptionId.WindowsDesktopDebuggers /Quiet /NoRestart /L
og "C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\windows-sdk-10
-version-2004-windbg_91c1f58a-b438-4dfc-8b39-dc1759426e06.log" ] exited with '15
605'.
2020-12-24 10:12:58,943 31152 [ERROR] - ERROR: Running ["C:\Users\ContainerAdmin
istrator\AppData\Local\Temp\chocolatey\windows-sdk-10-version-2004-windbg\10.0.1
9041.0\winsdksetup.exe" /Features OptionId.WindowsDesktopDebuggers /Quiet /NoRes
tart /Log "C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\windows
-sdk-10-version-2004-windbg_91c1f58a-b438-4dfc-8b39-dc1759426e06.log" ] was not
successful. Exit code was '15605'. See log for possible error messages.
2020-12-24 10:12:58,945 31152 [DEBUG] - Built-in PowerShell host called with ['[
System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Th
read]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramDat
a\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\hel
pers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\w
indows-sdk-10-version-2004-windbg\tools\chocolateyinstall.ps1' -installArguments
 '' -packageParameters '''] exited with '15605'.
2020-12-24 10:12:58,947 31152 [DEBUG] - Calling command ['"C:\Windows\System32\s
hutdown.exe" /a']
2020-12-24 10:12:58,989 31152 [DEBUG] - Command ['"C:\Windows\System32\shutdown.
exe" /a'] exited with '1116'
2020-12-24 10:12:59,041 31152 [DEBUG] - Capturing package files in 'C:\ProgramDa
ta\chocolatey\lib\windows-sdk-10-version-2004-windbg'
2020-12-24 10:12:59,042 31152 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\wi
ndows-sdk-10-version-2004-windbg\windows-sdk-10-version-2004-windbg.nupkg'
  with checksum 'D02A317BECF022F13B3664982C50D12A'
2020-12-24 10:12:59,043 31152 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\wi
ndows-sdk-10-version-2004-windbg\windows-sdk-10-version-2004-windbg.nuspec'
  with checksum 'C32F14BC6DE1419F2CBA2878A46A9D1A'
2020-12-24 10:12:59,043 31152 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\wi
ndows-sdk-10-version-2004-windbg\tools\chocolateyinstall.ps1'
  with checksum '36FAF4DBC282AB0E1AFF927A85AF11ED'
2020-12-24 10:12:59,052 31152 [DEBUG] - Attempting to create directory "C:\Progr
amData\chocolatey\.chocolatey\windows-sdk-10-version-2004-windbg.10.0.19041.0".
2020-12-24 10:12:59,059 31152 [DEBUG] - There was no original file at 'C:\Progra
mData\chocolatey\.chocolatey\windows-sdk-10-version-2004-windbg.10.0.19041.0\.fi
les'
2020-12-24 10:12:59,061 31152 [DEBUG] - Attempting to delete file "C:\ProgramDat
a\chocolatey\.chocolatey\windows-sdk-10-version-2004-windbg.10.0.19041.0\.argume
nts".
2020-12-24 10:12:59,061 31152 [DEBUG] - Attempting to delete file "C:\ProgramDat
a\chocolatey\.chocolatey\windows-sdk-10-version-2004-windbg.10.0.19041.0\.extra"
.
2020-12-24 10:12:59,062 31152 [DEBUG] - Attempting to delete file "C:\ProgramDat
a\chocolatey\.chocolatey\windows-sdk-10-version-2004-windbg.10.0.19041.0\.versio
n".
2020-12-24 10:12:59,062 31152 [DEBUG] - Attempting to delete file "C:\ProgramDat
a\chocolatey\.chocolatey\windows-sdk-10-version-2004-windbg.10.0.19041.0\.sxs".
2020-12-24 10:12:59,063 31152 [DEBUG] - Attempting to delete file "C:\ProgramDat
a\chocolatey\.chocolatey\windows-sdk-10-version-2004-windbg.10.0.19041.0\.pin".
2020-12-24 10:12:59,064 31152 [DEBUG] - Sending message 'HandlePackageResultComp
letedMessage' out if there are subscribers...
2020-12-24 10:12:59,065 31152 [ERROR] - The install of windows-sdk-10-version-20
04-windbg was NOT successful.
2020-12-24 10:12:59,067 31152 [ERROR] - Error while running 'C:\ProgramData\choc
olatey\lib\windows-sdk-10-version-2004-windbg\tools\chocolateyinstall.ps1'.
 See log for details.
2020-12-24 10:12:59,068 31152 [DEBUG] - Attempting to create directory "C:\Progr
amData\chocolatey\\AppData\Local\NuGet\Cache\windows-sdk-10-version-2004-windbg.
10.0.19041.0.nupkg".
2020-12-24 10:13:01,079 31152 [WARN ] -
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2020-12-24 10:13:01,080 31152 [INFO ] -
2020-12-24 10:13:01,081 31152 [ERROR] - Failures
2020-12-24 10:13:01,081 31152 [ERROR] -  - windows-sdk-10-version-2004-windbg (e
xited 15605) - Error while running 'C:\ProgramData\chocolatey\lib\windows-sdk-10
-version-2004-windbg\tools\chocolateyinstall.ps1'.
 See log for details.
2020-12-24 10:13:01,082 31152 [DEBUG] - Sending message 'PostRunMessage' out if
there are subscribers...
2020-12-24 10:13:01,091 31152 [DEBUG] - Exiting with 15605
```

My Docker desktop version is v20.10.0.
How to solve this? This problem has troubled me for a long time. Thanks a lot~

**Comment by arisona** [comment] 2020-12-24 09:39
Likely a duplicate of #122

**Comment by stone002** [comment] 2020-12-24 10:06
> Likely a duplicate of #122

yeah, but we have different exit code.

**Comment by stone002** [comment] 2020-12-25 02:39
> Likely a duplicate of #122

Hi arisona, I found that if I add "dns": ["8.8.8.8"] to my docker json file, my error is totally same with #122 . So I will close this issue and follow your's.

**Closed** 2020-12-25 02:40 UTC
