### ISSUE TITLE
Feature Request: Disable `git status` checks for adaptive non-unity build

### ISSUE THREAD

**Issue by TBBle** [adamrehn/ue4-docker#111] opened 2020-11-03 08:36 UTC
I noticed this in the logs of a build under Hyper-V isolation on Windows:
```
  Using 'git status' to determine working set for adaptive non-unity build (C:\UnrealEngine).
  Waiting for 'git status' command to complete
  Terminating git child process due to timeout
```

Presumably this timeout is due to either CPU starvation due to lack of cores in the VM (https://github.com/moby/moby/issues/38387), or general IO awfulness under Hyper-V isolation.

Either way, calling `git status` at all seems needless, since any source changes will invalidate the Docker cache all the way back in ue4-source, so build outputs in ue4-minimal are never going to see incremental builds.

Is it possible for ue4-docker to default to disabling the adaptive non-unity build?

I haven't checked if this is a parameter we can pass into BuildGraph, or if it would require live-patching or something, so I don't know if this is easy or hard.

And since my machine is busy this week with the aforementioned Hyper-V build, I can't currently experiment with this. Maybe in a couple of weeks, unless someone resolves this (either way) before then.

**Comment by TBBle** [comment] 2020-11-03 08:38
Thinking about it, does it make sense for the final ue4-source image to even _contain_ the _.git_ folder? Are there any interesting git operations that might be done by the build, given we already override the build version metadata to simulate the appropriate P4 changelist for the tag anyway?

**Comment by adamrehn** [comment] 2020-11-03 10:42
I'm not sure that it would be practical to remove the `.git` directory, since removing it in any RUN directive other than the one in which it is created would inflate the final image size, and the ue4-source image is already humongous as it is. I suppose it would be possible to rework the Dockerfile to use a single RUN directive for cloning and post-clone setup steps, but such a change would require extensive testing to prevent breakage.

Once my testing harness is complete, I'll have a look at the two options (disabling this behaviour programmatically .vs. removing the `.git` directory entirely) and see which one is easier to implement.

**Comment by TBBle** [comment] 2020-11-03 15:30
I'd be surprised if deleting the .git in a new `RUN` line inflated the final image size significantly. A deletion should just [name the file or directory to delete](https://github.com/opencontainers/image-spec/blob/master/layer.md#whiteouts), so it should be a _very_ small image layer.

It won't _reclaim_ the size of _.git_ from the image on-disk or uploaded, because that data exists in a previous layer which is still extracted to disk. Avoiding this is the usual reason for the big long chains of `RUN curl X && ./X && rm X`, so simply deleting the .git folder shouldn't be a significant regression in image size, but it won't be an improvement.

**Comment by adamrehn** [comment] 2020-12-22 00:57
Okay, GitHub seems to be trolling me, because the comment I posted here yesterday has mysteriously vanished. Here's the short version:

- I couldn't find any mention of unity builds in the Build Graph XML, so removing the `.git` directory seems to be the way to go.

- With no `.git` directory present, the fallback behaviour is to assume that the user is using Perforce and has file locking enabled, so it just checks whether files are read-only. I had links to the exact lines of code in the original version of this dot point so you could see the behaviour, but TLDR is that it never tries to actually invoke Perforce so it won't give us any grief.

- Removing the `.git` directory in the `ue4-source` image could interfere with the use cases for the `ue4-engine` image, so I'm going to remove it at the start of the `ue4-minimal` image instead. This actually renders the size discussion moot, but for what it's worth, my testing confirmed that the layer where the deletion is performed is tiny (sub-1KiB.)

**Comment by adamrehn** [comment] 2020-12-22 00:58
And now for the comment I actually came here to post today. My tests showed that 4.26.0 built fine under both Windows and Linux, so I'm gonna tag a release with the change from yesterday.

**Comment by adamrehn** [comment] 2020-12-22 01:03
Right, this is now live in ue4-docker version 0.0.75. Before I close the issue, I'm gonna try posting a comment with the same hyperlinks that the vanished one had and see if GitHub leaves it alone:

**Comment by adamrehn** [comment] 2020-12-22 01:08
- The lines of code for the Perforce implementation of `ISourceFileWorkingSet`: [4.26.0 version](https://github.com/EpicGames/UnrealEngine/blob/4.26.0-release/Engine/Source/Programs/UnrealBuildTool/System/SourceFileWorkingSet.cs#L67-L84), unchanged all the way back to [4.19.2](https://github.com/EpicGames/UnrealEngine/blob/4.19.2-release/Engine/Source/Programs/UnrealBuildTool/System/SourceFileWorkingSet.cs#L67-L84).

- The Perforce KB article about [Exclusive File Locking](https://community.perforce.com/s/article/3114)

- The ue4-docker docs page for the [Developing Engine modifications](https://docs.adamrehn.com/ue4-docker/use-cases/developing-engine-modifications) use case

- The commit where I added the `RUN` directives to remove the `.git` directory: 9c0429c

**Comment by adamrehn** [comment] 2020-12-22 01:11
Okay, that seems to be sticking this time. I guess GitHub just had a hiccup when I posted the original one.

**Closed by adamrehn** 2020-12-22 01:11 UTC

**Comment by slonopotamus** [comment] 2021-03-11 07:41
This change (pruning of `.git` directory) was somewhat improved by 9cf1375c33098a2787b5f514fd0ff36167a12b96.

**Comment by TBBle** [comment] 2025-02-07 12:27
Since weirdly this ticket is the first hit on Google for "ue4 buildgraph disable read-only adaptive unity build" when I was trying to work out how to disable this same behaviour in UE 5.4 (outside ue4-docker), I thought I'd share what I learned while poking around:

You can [force the use of a particular `SourceFileWorkingSet` `Provider` in the BuildConfiguration.xml](https://dev.epicgames.com/documentation/en-us/unreal-engine/build-configuration-for-unreal-engine#sourcefileworkingset), so this:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Configuration xmlns="https://www.unrealengine.com/BuildConfiguration">
	<SourceFileWorkingSet>
		<Provider>None</Provider>
	</SourceFileWorkingSet>
</Configuration>
```

will cause UBT to not exclude anything from the unity builds. (The options are `None`, `Default` (auto-detect), `Perforce`, and `Git`)

So if anyone comes back to this ticket and wants their UE `.git` directory to not be removed, a temporary `BuildConfiguration.xml` might be an alternative solution here. Although I didn't check if this feature is new or not; I expect it always worked that way, but we didn't notice when looking into this four years ago.

(Also, looking at the docs, maybe simply setting `bUseAdaptiveUnityBuild` to false would also work, but I haven't tested that.)
