### ISSUE TITLE
To open this project you must first install NullSourceCodeAccessor. Would you like to install it now?

### ISSUE THREAD

**Issue by quentingllmt** [adamrehn/ue4-docker#154] opened 2021-04-16 18:37 UTC
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.81 (latest available version is 0.0.82)
Operating system:           Linux (Ubuntu 18.04.5 LTS, 4.15.0-141-generic)
Docker daemon version:      20.10.6
NVIDIA Docker supported:    Yes
Maximum image size:         No limit detected
Available disk space:       247.17 GiB
Total system memory:        31.27 GiB physical, 2 GiB virtual
Number of processors:       16 physical, 32 logical
```
(irrelevant)

Additional details:
ue4.25.4-opengl10.2
- Are you accessing the network through a proxy server? No

I'm trying to open a project with the editor but I get:
`To open this project you must first install NullSourceCodeAccessor. Would you like to install it now?`

I understand there are some codeaccessor plugins but what is the solution with ue4-docker ?
Thanks

**Comment by slonopotamus** [comment] 2021-05-18 10:18
> I'm trying to open a project with the editor but I get

Could you please elaborate on that? What command you're using?

**Comment by adamrehn** [comment] 2021-06-09 12:05
@quentingllmt some specific questions in case this makes it easier for you to elaborate:

- Are you [exporting the Installed Build to the host system](https://unrealcontainers.com/docs/use-cases/linux-installed-builds) or [running it interactively inside a container](https://unrealcontainers.com/docs/use-cases/linux-sandboxed-editor)?
- Are you attempting to open the project from the command-line or through the GUI?

**Comment by GuardedAirplane** [comment] 2021-06-10 14:01
I am not sure about op, but I ran into the same issue when trying to open the AirSim Blocks environment using the interactive docker container through the UE4 GUI.

I am not running the standard pip install version though. I added a CUDA 11.3 target (same Ubuntu 18.04 base image though) and built against that. I was unable to get the 10.2 version to run on my 3090.

**Comment by GuardedAirplane** [comment] 2021-06-10 15:24
I was able to solve it on my end by executing `sudo apt install kdevelop` inside the docker container. 

I also created a separate project (that always worked for me before the fix) and set KDevelop to the default editor, but given that still caused the original error until I actually installed it, I think this step is not required. There probably are other packages that you could install, but this worked for me and I don't care about the extra 1G of space consumed.

**Comment by slonopotamus** [comment] 2021-06-10 15:57
From the [engine source](https://github.com/EpicGames/UnrealEngine/blob/4.25.4-release/Engine/Source/Editor/GameProjectGeneration/Private/SProjectBrowser.cpp#L1079) it looks like that in order to hit "To open this project you must first install" message, `ProjectIdentifier != CurrentIdentifier` condition must trigger. So, it is true that you're trying to open a C++ project whose `.uproject` file has `EngineAssociation` that is different from the engine you're running?

**Comment by slonopotamus** [comment] 2021-06-10 20:39
I _think_ that if .uproject had proper engine version specified in advance, you would not need to do all this stuff with KDevelop. You case is not specific to ue4-docker in any way, you would get exactly the same behavior if Unreal Engine was built on the host system.

I am going to close this issue because
1. We don't want to add 1GBs to the image for such a corner case (and even if we added KDevelop, user would still need to use it in game configs)
2. It is expected behavior that if project is not adapted to target UE4 version, then some manual actions might be required (adjustments to .uproject, fixes to C++ code that might not compile, etc)

Normally, projects generated by Unreal Eng8ne only specify major.minor version in .uproject (like, "4.25"), so no action is needed when you upgrade to a patch release.

**Comment by Sanic** [comment] 2021-06-28 07:16
> I was able to solve it on my end by executing `sudo apt install kdevelop` inside the docker container.
> 
> I also created a separate project (that always worked for me before the fix) and set KDevelop to the default editor, but given that still caused the original error until I actually installed it, I think this step is not required. There probably are other packages that you could install, but this worked for me and I don't care about the extra 1G of space consumed.
> 
> EDIT: After further testing, it looks like setting the default editor to KDevelop is necessary.

Hi @GuardedAirplane 
I'm currently running into the same issue and was wondering if you could elaborate this workaround a bit more?
Did you also use an Installed Build in the end?
After creating a container with a full 4.25.4 build i've started the docker container interactively, installed kdevelop, commited the changes and exported this build. Unfortunately it yields the same error.

**Comment by slonopotamus** [comment] 2021-06-28 07:36
@Sanic

You just need to fix your project so it is compatible with engine version you're trying to open it with. In this particular case, you need to go to `.uproject` file and change `EngineAssociation` to `4.25`. And you don't need kdevelop to do that.

**Comment by Sanic** [comment] 2021-06-28 15:09
Hi @slonopotamus 
Thank you for your swift answer!
This helped me to find a solution, but please let me elaborate what i tried to do:

1) I'm encountering this problem/the error message already when i try to create a fresh C++ Project within the UE4Editor.

2) After your message, i've took an existing C++ project, set "4.25" in the EngineAssociation and tried to open it via the GUI dialog within the UE4Editor. Unfortunately this didn't work, because the Editor tells me that i need to install the NullSourceCodeAccessor in order to open this project.

3)When i try to call the UE4 project directly from the CLI via path/to/installeduebuild/UE4Editor full/path/to/uproject , the UE4Editor asks me to confirm if i wanna build the modules. 
This worked for me!

I'm still wondering why the UE4Editor dialog to create and load projects behaves like that, even when the Engine association is set to 4.25...

**Comment by slonopotamus** [comment] 2021-06-28 15:29
Let's reopen this issue since there's something fishy is going on and deserves additional investigation...

**Comment by slonopotamus** [comment] 2021-06-28 15:31
So, you say that opening via GUI produces an error even if project has correct `EngineAssociation`. Interesting, I need to run some tests locally.

**Comment by Sanic** [comment] 2021-07-01 15:42
Exactly!
As an example:
I've got one UE4.25 project which is set to:
`    "EngineAssociation": "4.25"`

If i open this project via the bash with:
`~/UnrealInstalled/Engine/Binaries/Linux/UE4Editor "path/to/project.uproject"`
it loads just fine and also compiles C++ modules/plugins in the project.

If i just open ~/UnrealInstalled/Engine/Binaries/Linux/UE4Editor , the GUI shows the project:
![ue4_gui](https://user-images.githubusercontent.com/710969/124152031-72712f00-da93-11eb-9996-53772aee62cb.png)
but as soon as you hit 'open', the following error appears:
![ue4_gui_error](https://user-images.githubusercontent.com/710969/124152034-73a25c00-da93-11eb-94c7-68ff323a82ff.png)

**Comment by slonopotamus** [comment] 2021-07-01 16:08
Okaaay, engine from ue4-docker does **not** think that it is 4.25. See that project icon is greyed out on your screenshot. And if you create new projects with engine, it writes guid into `EngineAssociation` instead of engine version.

P.S. I was easily able to reproduce it locally.

**Comment by slonopotamus** [comment] 2021-07-01 16:16
So, we need to convince `FDesktopPlatformBase::GetEngineIdentifierFromRootDir` that our identifier is 4.25.

Note to myself: `~/.config/Epic/UnrealEngine/Install.ini`, `FDesktopPlatformLinux::EnumerateEngineInstallations`.

**Comment by adamrehn** [comment] 2021-09-10 02:00
My understanding is that the other factor in triggering this issue is that when Unreal Engine 4.25 and older default to the `NullSourceCodeAccessor` (rather than an IDE like KDevelop), the check for whether a compiler is available fails due to an outdated check for a system installation of clang. This bug was [fixed in 4.26.0](https://github.com/EpicGames/UnrealEngine/commit/ee428aa5712410c24b078fef619eaced98acb6ea), so it might be worth checking to see whether the error messages are resolved under newer Engine versions. If so, then there should be no need to mess around with `EngineAssociation` values.

**Comment by slonopotamus** [comment] 2022-04-26 11:17
There's one more reason why we want `EngineAssociation`:

Attempt to run [InspectCode](https://www.jetbrains.com/help/resharper/InspectCode.html) inside ue4-docker image results in

```
Warning: C:\ProgramData\Epic\UnrealEngineLauncher\LauncherInstalled.dat doesn't exist
Warning: Failed to find Unreal Engine for C:\builds\MyProject.uproject with EngineAssociation=my_engine_association!
```

Now the question is: how we figure out what string to use for engine association.

**Comment by adamrehn** [comment] 2024-02-07 06:08
Circling back around to this a couple of years later: Epic finally added the [necessary functionality for Linux Installed Builds to be recognised as Launcher builds](https://github.com/EpicGames/UnrealEngine/commit/af3dc341fdcadc236b6866a5763657c57eeb9eef) in Unreal Engine 5.3.1, which allows projects from macOS and Windows to be opened without prompting for conversion. The relevant logic relies on a custom Build ID being specified when the Installed Build is created, and the string must be in the form `UE_<Major>.<Minor>` (e.g. `UE_5.3`). The `UE_` prefix is stripped when resolving engine associations for `.uproject` files, so a project file with `"EngineAssociation": "5.3"` will match an Installed Build with the Build ID `UE_5.3`.

I've added logic in commit 84ca65c to ensure that any custom Build ID specified during creation of the Installed Build is correctly reflected in `Install.ini`, so setting the correct Build ID can now be achieved like so:

```bash
# Set the appropriate Build ID to match Epic's official binaries (in this case, for 5.3.1 or 5.3.2)
ue4-docker build --opt buildgraph-args="-set:BuildIdOverride=UE_5.3" <remaining args here>
```

**Closed by adamrehn** 2024-02-07 06:08 UTC
Labels: question
