### ISSUE TITLE
don't install installed package

### ISSUE THREAD

**Issue by Ludea** [adamrehn/ue4-docker#13] opened 2018-11-12 08:13 UTC
Hello,

I have already cmake on my OS.
During Windows build I have this message:
`ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\cmake.install\tools\cmake-3.12.4-win64-x64.msi" /qn /norestart /l*v "C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\cmake.install.3.12.4.MsiInstall.log" ADD_CMAKE_TO_PATH=System] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\cmake.install_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
2018-11-11T21:03:27.7104984Z cmake not installed. An error occurred during installation:`

I think it is related with cmake installation. ( I can not modify it, it is on cloud CI).
You shoud verify if one of the prerequis are already installed.
Thanks

**Comment by adamrehn** [comment] 2018-11-12 08:57
What exactly do you mean when you say that you already have CMake on your OS? Have you modified the Dockerfiles in some way, or are you attempting to run the commands from the Dockerfile on the host operating system? The presence of software installed on the host OS cannot interfere with the containers, since they run in a sandbox by their very nature and are entirely isolated from the filesystem of the host environment.

**Comment by Ludea** [comment] 2018-11-12 09:50
I don't modify nothing.
My host is windows server 2016, with cmake installed. 
I launch the script both on Linux and Windows. 
On Linux the build is successful but on windows, cmake installation is "broken" with the above message. 
The ci provider I use is azure devops

**Comment by adamrehn** [comment] 2018-11-12 09:57
Hmmm, in that case the presence of CMake on the host OS shouldn't cause any issues. Looking at the version history for the CMake Chocolatey package, I can see that a new version was uploaded recently, so perhaps the issue is with the current version of the package. I will investigate further and let you know what I find.

**Comment by Ludea** [comment] 2018-11-13 17:52
I update to 0.04, still have issue.
Here the logs:
```
2018-11-13T17:33:19.8592647Z Progress: Downloading cmake 3.12.4... 100%
2018-11-13T17:33:20.2365615Z 
2018-11-13T17:33:20.2366372Z cmake.install v3.12.4 - Possibly broken
2018-11-13T17:33:20.2479139Z cmake.install package files install completed. Performing other installation steps.
2018-11-13T17:33:21.0919535Z Installing 64-bit cmake.install...
2018-11-13T17:33:27.1991589Z WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\cmake.install_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
2018-11-13T17:33:27.2435294Z ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\cmake.install\tools\cmake-3.12.4-win64-x64.msi" /qn /norestart /l*v "C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\cmake.install.3.12.4.MsiInstall.log" ADD_CMAKE_TO_PATH=System] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\cmake.install_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
2018-11-13T17:33:27.2573264Z cmake not installed. An error occurred during installation:
2018-11-13T17:33:27.2573838Z  The system cannot find the file specified
2018-11-13T17:33:27.2583605Z cmake package files install completed. Performing other installation steps.
2018-11-13T17:33:27.2979280Z This is try 1/3. Retrying after 300 milliseconds.
2018-11-13T17:33:27.2979589Z  Error converted to warning:
2018-11-13T17:33:27.2979773Z  (2) The system cannot find the file specified: [\\?\C:\ProgramData]
2018-11-13T17:33:27.5992857Z This is try 2/3. Retrying after 400 milliseconds.
2018-11-13T17:33:27.5993180Z  Error converted to warning:
2018-11-13T17:33:27.5993347Z  (2) The system cannot find the file specified: [\\?\C:\ProgramData]
2018-11-13T17:33:28.0014004Z Maximum tries of 3 reached. Throwing error.
2018-11-13T17:33:28.0028314Z Cannot create directory "C:\ProgramData\chocolatey\.chocolatey". Error was:
2018-11-13T17:33:28.0028626Z System.IO.FileNotFoundException: (2) The system cannot find the file specified: [\\?\C:\ProgramData]
2018-11-13T17:33:28.0028842Z    at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
2018-11-13T17:33:28.0029049Z    at Alphaleonis.Win32.Filesystem.Directory.CreateDirectoryCore(KernelTransaction transaction, String path, String templatePath, ObjectSecurity directorySecurity, Boolean compress, PathFormat pathFormat)
2018-11-13T17:33:28.0031788Z    at Alphaleonis.Win32.Filesystem.Directory.CreateDirectory(String path)
2018-11-13T17:33:28.0032019Z    at chocolatey.infrastructure.filesystem.DotNetFileSystem.<>c__DisplayClass64.<create_directory>b__63()
2018-11-13T17:33:28.0032201Z    at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1.<retry>b__0()
2018-11-13T17:33:28.0032366Z    at chocolatey.infrastructure.tolerance.FaultTolerance.retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
2018-11-13T17:33:28.0032545Z    at chocolatey.infrastructure.filesystem.DotNetFileSystem.create_directory(String directoryPath)
2018-11-13T17:33:28.0032717Z    at chocolatey.infrastructure.filesystem.DotNetFileSystem.create_directory_if_not_exists(String directoryPath, Boolean ignoreError)
2018-11-13T17:33:28.0109445Z (2) The system cannot find the file specified: [\\?\C:\ProgramData]
2018-11-13T17:33:28.8171778Z The command 'cmd /S /C choco install -y git --params "'/GitOnlyOnPath /NoAutoCrlf /WindowsTerminal /NoShellIntegration /NoCredentialManager'" && 	choco install -y curl python vcredist-all && 	choco install -y cmake --installargs "ADD_CMAKE_TO_PATH=System"' returned a non-zero code: 1
2018-11-13T17:33:28.9885221Z [ue4-docker build] Error: failed to build image "adamrehn/ue4-build-prerequisites:latest".
2018-11-13T17:33:32.1181360Z ##[error]Cmd.exe exited with code '1'.
2018-11-13T17:33:32.4532265Z ##[section]Finishing: Build Engine```

**Comment by adamrehn** [comment] 2018-11-13 22:42
Yes, 0.0.4 has the same Dockerfile contents as 0.0.3, so the build will behave in exactly the same way. The purpose of updating to 0.0.4 is so that you can run the `ue4-docker info` command, which was added in 0.0.4.

Looking at the log output from the build it appears to be having an issue with the directory `C:\ProgramData`, which is rather strange. As per my previous comment, could you please run the command `ue4-docker info` and paste the output here so that I can see the details of the system on which the build is running? This will help me in reproducing the error so that I can diagnose the problem.

**Comment by Ludea** [comment] 2018-11-14 23:41
Here the logs of `ue4-docker info `
```2018-11-14T23:39:16.9285054Z Generating script.
2018-11-14T23:39:16.9411563Z Script contents:
2018-11-14T23:39:16.9417935Z ue4-docker info
2018-11-14T23:39:17.0022354Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\ec4909ee-5d78-4b25-b41f-f92a9a1c8f77.cmd""
2018-11-14T23:39:18.6835655Z ue4-docker version:         0.0.4
2018-11-14T23:39:18.6835846Z Operating system:           Windows Server 2016 Datacenter Version 1607 (OS Build 14393.2485)
2018-11-14T23:39:18.6835966Z Docker daemon version:      18.03.1-ee-3
2018-11-14T23:39:18.6836012Z NVIDIA Docker supported:    No
2018-11-14T23:39:18.6836100Z Maximum image size:         20GB
2018-11-14T23:39:18.6836356Z Total system memory:        7 GiB
2018-11-14T23:39:18.6836406Z Number of processors:       2 physical, 2 logical
2018-11-14T23:39:18.7534460Z ##[section]Finishing: info```

**Comment by adamrehn** [comment] 2018-11-15 03:34
That's strange. The output line `Maximum image size: 20GB` suggests that you haven't configured the maximum image size to the recommended minimum of 200GB, but `ue4-docker build` should prevent you from attempting to build the images at all if this minimum is not configured correctly. Is this command running in the same environment as the build command was? If so, perhaps a bug in the size detection is allowing the build to run despite the 20GB image size limit, which could explain the cryptic error related to the `C:\ProgramData` directory. One way to check this would be to run `ue4-docker setup` immediately before `ue4-docker build`, which should ensure the size limit is configured correctly.

**Comment by adamrehn** [comment] 2018-11-20 04:31
I'm closing this issue for the time being, since the problem appears to stem from incorrect host system configuration, and version 0.0.5 of ue4-docker has now moved CMake to the `ue4-full` image under Windows anyway.

If you still see the same error during CMake installation under version 0.0.5 of ue4-docker then feel free to comment here and I'll reopen the issue, since any problems that stem from incorrect configuration should manifest themselves long before that step is reached.

**Closed by adamrehn** 2018-11-20 04:31 UTC
