### ISSUE TITLE
Unable to build engine on Phenom II

### ISSUE THREAD

**Issue by Elrendir95** [adamrehn/ue4-docker#250] opened 2022-05-04 20:48 UTC
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.98 (latest available version is 0.0.98)
Operating system:           Linux (Debian GNU/Linux 11 (bullseye), 5.16.0-0.bpo.4-amd64)
Docker daemon version:      20.10.14
NVIDIA Docker supported:    No
Maximum image size:         No limit detected
Available disk space:       126.9 GiB
Total system memory:        15.35 GiB physical, 975 MiB virtual
CPU:                        6 physical, 6 logical ()
```

Additional details:

- Are you accessing the network through a proxy server? **No**

I was trying to build an docker image of the version 5.0 of the UnrealEngine I had forked few weeks ago, but I am gettings thoses errors : 

```
#19 298.1   Running UnrealHeaderTool UnrealEditor "/home/ue4/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UnrealEditor/DebugGame/UnrealEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="/home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/UHT-UnrealEditor-Linux-DebugGame.txt"
#19 298.3 Took 4.9666545s to run UnrealBuildTool, ExitCode=3
#19 298.3 UnrealBuildTool failed. See log for more details. (/home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/UBT-UnrealEditor-Linux-DebugGame.txt)
#19 298.3 AutomationTool executed for 0h 4m 45s
#19 298.3 AutomationTool exiting with ExitCode=3 (Error_UnknownCommand)
#19 298.4 RunUAT ERROR: AutomationTool was unable to run successfully. Exited with code: 3
------
executor failed running [/bin/sh -c ./Engine/Build/BatchFiles/RunUAT.sh BuildGraph     -target="Make Installed Build Linux"     -script=Engine/Build/InstalledEngineBuild.xml     -set:WithDDC=true -set:HostPlatformOnly=true &&       rm -R -f /home/ue4/UnrealEngine/LocalBuilds/InstalledDDC && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo '']: exit code: 3
[ue4-docker build] Error: failed to build image "adamrehn/ue4-minimal:5.0-opengl-ubuntu18.04".
```

If you have any idee how I could fix this

Thx

Full output of the build : 
```
[ue4-docker build] COMMAND-LINE INVOCATION:
[ue4-docker build] ['ue4-docker', 'custom:5.0', '--target=full', '--exclude', 'templates', '-repo=https://github.com/Elrendir95/UnrealEngine.git', '-branch=5.0']

[ue4-docker build] UNREAL ENGINE VERSION SETTINGS:
[ue4-docker build] Custom build:  Yes
[ue4-docker build] Custom name:   5.0
[ue4-docker build] Repository:    https://github.com/Elrendir95/UnrealEngine.git
[ue4-docker build] Branch/tag:    5.0

[ue4-docker build] ADVANCED CONFIGURATION OPTIONS:
[ue4-docker build] buildgraph_args: "-set:HostPlatformOnly=true"
[ue4-docker build] excluded_components: {"ddc": false, "debug": false, "templates": true}

[ue4-docker build] LINUX CONTAINER SETTINGS
[ue4-docker build] Base OS image: nvidia/opengl:1.0-glvnd-devel-ubuntu18.04

[ue4-docker build] GENERAL SETTINGS
[ue4-docker build] Build targets: build-prerequisites full minimal source
[ue4-docker build] Changelist override: (None specified)
[ue4-docker build] Excluding the following Engine components:
[ue4-docker build] - Template projects and samples
[ue4-docker build] Not building the ue4-source image, no Git credentials required.

[ue4-docker build] Image "adamrehn/ue4-build-prerequisites:opengl-ubuntu18.04" exists and rebuild not requested, skipping build.

[ue4-docker build] Image "adamrehn/ue4-source:5.0-opengl-ubuntu18.04" exists and rebuild not requested, skipping build.

[ue4-docker build] Skipping ue4-engine image build.

[ue4-docker build] Building image "adamrehn/ue4-minimal:5.0-opengl-ubuntu18.04"...
[+] Building 300.2s (19/32)
 => [internal] load build definition from Dockerfile                                                                                                                                               0.0s
 => => transferring dockerfile: 7.94kB                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                                  0.0s
 => => transferring context: 53B                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/adamrehn/ue4-build-prerequisites:opengl-ubuntu18.04                                                                                                     0.0s
 => [internal] load metadata for docker.io/adamrehn/ue4-source:5.0-opengl-ubuntu18.04                                                                                                              0.0s
 => CACHED [stage-1 1/7] FROM docker.io/adamrehn/ue4-build-prerequisites:opengl-ubuntu18.04                                                                                                        0.0s
 => [internal] load build context                                                                                                                                                                  0.0s
 => => transferring context: 9.97kB                                                                                                                                                                0.0s
 => [builder  1/20] FROM docker.io/adamrehn/ue4-source:5.0-opengl-ubuntu18.04                                                                                                                      0.0s
 => CACHED [builder  2/20] COPY set-changelist.py /tmp/set-changelist.py                                                                                                                           0.0s
 => CACHED [builder  3/20] RUN python3 /tmp/set-changelist.py /home/ue4/UnrealEngine/Engine/Build/Build.version $CHANGELIST && echo '' && echo 'RUN directive complete. Docker will now commit th  0.0s
 => CACHED [builder  4/20] RUN rm -rf /home/ue4/UnrealEngine/.git && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large   0.0s
 => CACHED [builder  5/20] COPY enable-opengl.py /tmp/enable-opengl.py                                                                                                                             0.0s
 => CACHED [builder  6/20] RUN python3 /tmp/enable-opengl.py /home/ue4/UnrealEngine/Engine/Config/BaseEngine.ini && echo '' && echo 'RUN directive complete. Docker will now commit the filesyste  0.0s
 => CACHED [builder  7/20] COPY patch-filters-xml.py /tmp/patch-filters-xml.py                                                                                                                     0.0s
 => CACHED [builder  8/20] RUN python3 /tmp/patch-filters-xml.py /home/ue4/UnrealEngine/Engine/Build/InstalledEngineFilters.xml && echo '' && echo 'RUN directive complete. Docker will now commi  0.0s
 => CACHED [builder  9/20] COPY patch-build-graph.py /tmp/patch-build-graph.py                                                                                                                     0.0s
 => CACHED [builder 10/20] RUN python3 /tmp/patch-build-graph.py /home/ue4/UnrealEngine/Engine/Build/InstalledEngineBuild.xml /home/ue4/UnrealEngine/Engine/Build/Build.version && echo '' && ech  0.0s
 => CACHED [builder 11/20] RUN ./Engine/Build/BatchFiles/Linux/Build.sh UnrealHeaderTool Linux Development -SkipBuild && echo '' && echo 'RUN directive complete. Docker will now commit the file  0.0s
 => CACHED [builder 12/20] WORKDIR /home/ue4/UnrealEngine                                                                                                                                          0.0s
 => ERROR [builder 13/20] RUN ./Engine/Build/BatchFiles/RunUAT.sh BuildGraph     -target="Make Installed Build Linux"     -script=Engine/Build/InstalledEngineBuild.xml     -set:WithDDC=true -  300.0s
------
 > [builder 13/20] RUN ./Engine/Build/BatchFiles/RunUAT.sh BuildGraph     -target="Make Installed Build Linux"     -script=Engine/Build/InstalledEngineBuild.xml     -set:WithDDC=true -set:HostPlatformOnly=true &&    rm -R -f /home/ue4/UnrealEngine/LocalBuilds/InstalledDDC && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo '':
#19 0.494
#19 0.494 Running AutomationTool...
#19 0.494
#19 1.488 Fixing inconsistent case in filenames.
#19 1.492 Setting up Mono
#19 1.500 Setting up bundled DotNet SDK
#19 1.525 Rebuilding: AutomationTool assembly not found
#19 12.13 Start UAT Interactively: ./AutomationTool BuildGraph -target=Make Installed Build Linux -script=Engine/Build/InstalledEngineBuild.xml -set:WithDDC=true -set:HostPlatformOnly=true
#19 12.38 Parsing command line: BuildGraph -target="Make Installed Build Linux" -script=Engine/Build/InstalledEngineBuild.xml -set:WithDDC=true -set:HostPlatformOnly=true
#19 16.11 Building 20 projects (see Log 'Engine/Programs/AutomationTool/Saved/Logs/Log.txt' for more details)
#19 16.12  Restore...
#19 26.22  Build...
#19 45.99  build complete.
#19 46.17 Log location: /home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/Log.txt
#19 46.80 ****** [1/10] Update Version Files
#19 46.80
#19 46.82 /home/ue4/UnrealEngine
#19 46.82 Saving file list to /home/ue4/UnrealEngine/Engine/Saved/BuildGraph/Update Version Files/Tag-Update Version Files.xml
#19 46.83
#19 46.83 ****** [2/10] Compile UnrealHeaderTool Linux
#19 46.83
#19 46.83 Reading local file list from /home/ue4/UnrealEngine/Engine/Saved/BuildGraph/Update Version Files/Tag-Update Version Files.xml
#19 46.85 Running: /home/ue4/UnrealEngine/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool UnrealHeaderTool Linux Development  -NoUBTMakefiles -nobuilduht -precompile -allmodules -Manifest=/home/ue4/UnrealEngine/Engine/Intermediate/Build/Manifest.xml -NoHotReload -log="/home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/UBT-UnrealHeaderTool-Linux-Development.txt"
#19 47.24 Log file: /home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/UBT-UnrealHeaderTool-Linux-Development.txt
#19 48.72 Writing dependency list to /home/ue4/UnrealEngine/Engine/Intermediate/DependencyLists/UnrealHeaderTool/Development/Linuxx86_64-unknown-linux-gnu/DependencyList-AllModules.txt
#19 48.73 Writing manifest to /home/ue4/UnrealEngine/Engine/Intermediate/Build/Manifest.xml
#19 48.90 Building UnrealHeaderTool...
#19 48.90 [Adaptive Build] Excluded from BuildSettings unity file: BuildSettings.cpp
#19 48.90 [Adaptive Build] Excluded from NetCommon unity file: NetCommonModule.cpp
#19 48.91 Determining max actions to execute in parallel (6 physical cores, 6 logical cores)
#19 48.91   Executing up to 6 processes, one per physical core
#19 48.91   Requested 1.5 GB free memory per action, 7.68 GB available: limiting max parallel actions to 5
#19 48.92 Building 61 actions with 5 processes...
#19 49.03 [1/61] Compile BuildSettings.cpp
#19 52.61 [2/61] Compile SharedPCH.Core.ShadowErrors.h
#19 52.73 [3/61] Compile PCH.Core.h
#19 52.88 [4/61] Compile MiMalloc.c
#19 54.10 [5/61] Compile Module.TraceLog.cpp
#19 54.92 [6/61] Compile PCH.CoreUObject.h
#19 56.34 [7/61] Compile SharedPCH.Core.ShadowErrors.TypeCastWarnings.h
#19 70.63 [8/61] Compile Module.Core.18_of_18.cpp
#19 75.47 [9/61] Compile Module.Core.13_of_18.cpp
#19 83.78 [10/61] Compile Module.Core.9_of_18.cpp
#19 88.83 [11/61] Compile Module.Core.10_of_18.cpp
#19 90.18 [12/61] Compile Module.Core.8_of_18.cpp
#19 91.46 [13/61] Compile Module.Core.7_of_18.cpp
#19 115.8 [14/61] Compile Module.Core.17_of_18.cpp
#19 116.0 [15/61] Compile Module.Core.12_of_18.cpp
#19 120.3 [16/61] Compile Module.Core.1_of_18.cpp
#19 121.5 [17/61] Compile Module.Core.2_of_18.cpp
#19 130.7 [18/61] Compile Module.Core.14_of_18.cpp
#19 130.7 [19/61] Compile Module.Core.4_of_18.cpp
#19 139.6 [20/61] Compile Module.Core.5_of_18.cpp
#19 143.5 [21/61] Compile Module.Core.15_of_18.cpp
#19 146.5 [22/61] Compile Module.Core.11_of_18.cpp
#19 146.7 [23/61] Compile Module.SSL.cpp
#19 148.1 [24/61] Compile Module.Sockets.cpp
#19 149.3 [25/61] Compile Module.Zen.cpp
#19 170.8 [26/61] Compile Module.Core.6_of_18.cpp
#19 174.1 [27/61] Compile Module.Projects.cpp
#19 181.1 [28/61] Compile Module.Core.16_of_18.cpp
#19 189.6 [29/61] Compile Module.CoreUObject.6_of_10.cpp
#19 210.0 [30/61] Compile Module.DerivedDataCache.cpp
#19 214.5 [31/61] Compile Module.CoreUObject.3_of_10.cpp
#19 214.7 [32/61] Compile Module.CoreUObject.7_of_10.cpp
#19 215.0 [33/61] Compile Module.CoreUObject.10_of_10.cpp
#19 218.7 [34/61] Compile Module.CoreUObject.5_of_10.cpp
#19 223.7 [35/61] Compile SharedPCH.CoreUObject.ShadowErrors.h
#19 227.1 [36/61] Compile Module.CoreUObject.2_of_10.cpp
#19 246.3 [37/61] Compile Module.CoreUObject.8_of_10.cpp
#19 251.0 [38/61] Compile Module.CoreUObject.1_of_10.cpp
#19 251.1 [39/61] Link (lld) libUnrealHeaderTool-BuildSettings.so
#19 251.2 [40/61] Link (lld) libUnrealHeaderTool-TraceLog.so
#19 252.4 [41/61] Compile NetCommonModule.cpp
#19 259.0 [42/61] Compile Module.UnrealHeaderTool.2_of_2.cpp
#19 263.1 [43/61] Compile Module.Json.cpp
#19 264.8 [44/61] Compile Module.CoreUObject.9_of_10.cpp
#19 269.4 [45/61] Compile Module.ScriptGeneratorPlugin.cpp
#19 271.7 [46/61] Compile Module.Core.3_of_18.cpp
#19 276.3 [47/61] Compile Module.UnrealHeaderTool.1_of_2.cpp
#19 276.8 [48/61] Link (lld) libUnrealHeaderTool-Core.so
#19 276.9 [49/61] Link (lld) libUnrealHeaderTool-NetCommon.so
#19 277.1 [50/61] Link (lld) libUnrealHeaderTool-Json.so
#19 277.1 [51/61] Link (lld) libUnrealHeaderTool-SSL.so
#19 277.1 [52/61] Link (lld) libUnrealHeaderTool-Sockets.so
#19 277.4 [53/61] Link (lld) libUnrealHeaderTool-Zen.so
#19 277.5 [54/61] Link (lld) libUnrealHeaderTool-Projects.so
#19 278.5 [55/61] Link (lld) libUnrealHeaderTool-DerivedDataCache.so
#19 288.1 [56/61] Compile Module.CoreUObject.4_of_10.cpp
#19 291.5 [57/61] Link (lld) libUnrealHeaderTool-CoreUObject.so
#19 291.7 [58/61] Link (lld) libUnrealHeaderTool-ScriptGeneratorPlugin.so
#19 292.4 [59/61] Link (lld) UnrealHeaderTool
#19 292.8 [60/61] WriteMetadata UnrealHeaderTool.version
#19 293.1 [61/61] WriteMetadata UnrealHeaderTool.target
#19 293.1 Total time in Parallel executor: 244.22 seconds
#19 293.2 Total execution time: 246.14 seconds
#19 293.2 Took 246.3675208s to run UnrealBuildTool, ExitCode=0
#19 293.3 Saving local manifest to /home/ue4/UnrealEngine/Engine/Saved/BuildGraph/Compile UnrealHeaderTool Linux/Manifest.xml
#19 293.3 Saving file list to /home/ue4/UnrealEngine/Engine/Saved/BuildGraph/Compile UnrealHeaderTool Linux/Tag-Compile UnrealHeaderTool Linux.xml
#19 293.3
#19 293.3 ****** [3/10] Compile UnrealEditor Linux
#19 293.3
#19 293.3 Reading local file list from /home/ue4/UnrealEngine/Engine/Saved/BuildGraph/Compile UnrealHeaderTool Linux/Tag-Compile UnrealHeaderTool Linux.xml
#19 293.3 Reading local file list from /home/ue4/UnrealEngine/Engine/Saved/BuildGraph/Update Version Files/Tag-Update Version Files.xml
#19 293.3 Reading shared manifest from /home/ue4/UnrealEngine/Engine/Saved/BuildGraph/Compile UnrealHeaderTool Linux/Manifest.xml
#19 293.3 Running: /home/ue4/UnrealEngine/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool UnrealEditor Linux DebugGame  -NoUBTMakefiles -nobuilduht -precompile -allmodules  -Manifest=/home/ue4/UnrealEngine/Engine/Intermediate/Build/Manifest.xml -NoHotReload -log="/home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/UBT-UnrealEditor-Linux-DebugGame.txt"
#19 293.6 Log file: /home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/UBT-UnrealEditor-Linux-DebugGame.txt
#19 298.0 Parsing headers for UnrealEditor
#19 298.1   Running UnrealHeaderTool UnrealEditor "/home/ue4/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UnrealEditor/DebugGame/UnrealEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="/home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/UHT-UnrealEditor-Linux-DebugGame.txt"
#19 298.3 Took 4.9666545s to run UnrealBuildTool, ExitCode=3
#19 298.3 UnrealBuildTool failed. See log for more details. (/home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/UBT-UnrealEditor-Linux-DebugGame.txt)
#19 298.3 AutomationTool executed for 0h 4m 45s
#19 298.3 AutomationTool exiting with ExitCode=3 (Error_UnknownCommand)
#19 298.4 RunUAT ERROR: AutomationTool was unable to run successfully. Exited with code: 3
------
executor failed running [/bin/sh -c ./Engine/Build/BatchFiles/RunUAT.sh BuildGraph     -target="Make Installed Build Linux"     -script=Engine/Build/InstalledEngineBuild.xml     -set:WithDDC=true -set:HostPlatformOnly=true &&       rm -R -f /home/ue4/UnrealEngine/LocalBuilds/InstalledDDC && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo '']: exit code: 3
[ue4-docker build] Error: failed to build image "adamrehn/ue4-minimal:5.0-opengl-ubuntu18.04".
```

**Comment by slonopotamus** [comment] 2022-05-04 20:54
You're trying to build some non-released code from your own fork and that code doesn't compile. ue4-docker cannot do anything here. You should be able to `ue4-docker build --target=full 5.0.1-release` though.

**Comment by Elrendir95** [comment] 2022-05-05 20:22
Hello,
I do not know if this can help but I was doing the same steps as in the ue4-minimal Dockerfiles do get the Logs from the UnrealBuildTool : 
```
UnrealHeaderTool needs to run because no generated code directory was found for module CoreUObject
Parsing headers for UnrealEditor
  Running UnrealHeaderTool UnrealEditor "/home/ue4/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UnrealEditor/DebugGame/UnrealEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="/home/ue4/UnrealEngine/UHT-UnrealEditor-Linux-DebugGame.txt"
CompilationResultException: Error: CrashOrAssert
   at UnrealBuildTool.ExternalExecution.ExecuteHeaderToolIfNecessary(BuildConfiguration BuildConfiguration, FileReference ProjectFile, TargetMakefile Makefile, String TargetName, ISourceFileWorkingSet WorkingSet) in /home/ue4/UnrealEngine/Engine/Source/Programs/UnrealBuildTool/System/ExternalExecution.cs:line 1275
   at UnrealBuildTool.UEBuildTarget.Build(BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, TargetDescriptor TargetDescriptor) in /home/ue4/UnrealEngine/Engine/Source/Programs/UnrealBuildTool/Configuration/UEBuildTarget.cs:line 1773
   at UnrealBuildTool.BuildMode.CreateMakefile(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet) in /home/ue4/UnrealEngine/Engine/Source/Programs/UnrealBuildTool/Modes/BuildMode.cs:line 742
   at UnrealBuildTool.BuildMode.Build(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, Boolean bSkipPreBuildTargets) in /home/ue4/UnrealEngine/Engine/Source/Programs/UnrealBuildTool/Modes/BuildMode.cs:line 267
   at UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments) in /home/ue4/UnrealEngine/Engine/Source/Programs/UnrealBuildTool/Modes/BuildMode.cs:line 237
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in /home/ue4/UnrealEngine/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.cs:line 593
WriteFileIfChanged() wrote 0 changed files of 0 requested writes.
```

**Comment by TBBle** [comment] 2022-05-06 01:06
Unfortunately, that is just UBT telling us that UHT crashed. I assume the logs from UHT are in `/home/ue4/UnrealEngine/UHT-UnrealEditor-Linux-DebugGame.txt`, and hopefully will tell us the actual failure.

**Comment by Elrendir95** [comment] 2022-05-06 09:30
UHT actually crashed at the start with some "Illegal Instruction" the the logs file are not even created.

But I found [this](https://forums.unrealengine.com/t/unable-to-build-unreal-engine-on-ubuntu-18-04/151053/19) on Unreal forums, and it could be related to the CPU and the Clang version used.

I will try on other docker host that have on other CPU.

**Comment by slonopotamus** [comment] 2022-05-06 11:15
The problem is not SSE3, but [SSSE3](https://github.com/EpicGames/UnrealEngine/blob/5.0.1-release/Engine/Source/Programs/UnrealBuildTool/Platform/Linux/LinuxToolChain.cs#L583) that Phenom II lacks.

**Comment by Elrendir95** [comment] 2022-05-06 13:04
Thx,

I will try to edit the [`Engine/Source/Programs/UnrealBuildTool/Platform/Linux/LinuxToolChain.cs`](https://github.com/EpicGames/UnrealEngine/blob/5.0.1-release/Engine/Source/Programs/UnrealBuildTool/Platform/Linux/LinuxToolChain.cs#L583) to remove the `-mssse3`.
And if this is working I will try to edit/write a patch-xxx.py like the one you already to remove it depending on presence of the 
of the in `/proc/cpuinfo`

I will keep you inform

**Comment by TBBle** [comment] 2022-05-07 05:33
Maybe worth a bug-report to Epic, since I expect the same problem happens if you do the build on the host outside Docker too. They could at least update their documentation to specify a stronger build-system requirement than merely [_recommending_ "Quad-core Intel or AMD, 2.5 GHz or faster"](https://docs.unrealengine.com/5.0/en-US/hardware-and-software-specifications-for-unreal-engine/).

Also, sorry for any confusion from me missing the difference between SSE3 and SSSE3. I had somehow never _heard_ of the latter before now. >_< (Looking back at my search results when I was looking into this, I'm not the only one to have had this confusion. ^_^)

**Comment by Elrendir95** [comment] 2022-05-07 19:55
@slonopotamus Yes doubt it to, but I have nothing to lose to try :)

@TBBle
 I have just submit the issue to Epic.
From what I see in the tags this have been added with the 4.26.0-release, so yes not spécifique to the UE5

And no problem for the confusion ;)

**Comment by slonopotamus** [comment] 2022-05-11 19:22
I start to think that [this comment](https://github.com/EpicGames/UnrealEngine/blob/5.0.1-release/Engine/Source/Programs/UnrealBuildTool/Platform/Linux/LinuxToolChain.cs#L583) lies. Here's a one-year-old video of guys playing Fortnite on Phenom II: https://www.youtube.com/watch?v=eU5CkmLBHwM

So, at least one year ago, Windows UE builds didn't require SSSE3.

I was also unable to find any means to control SSSE3 in `cl.exe` flags, so "This is default on for MSVC" makes even less sense.

**Comment by TBBle** [comment] 2022-05-12 12:02
It's possible the person was confused like I was, since SSE3 has been present (AFAICT) from almost the very beginning of x86_64. It wasn't in the very first AMD x86_64 CPUs, but later revisions of the same chip lines (Opteron, Athlon 64) included it, and it seems all x86_64 Intel CPUs included it. I'm guessing MSVC has no flags for SSE3 onwards because their code-gen either generates SSE2 (which is part of the x86_64 base spec), or one of the AVX variants, presumably that being a difference that actually brings some benefit at the cost of compatibility.

**Comment by slonopotamus** [comment] 2022-05-12 12:16
Let's go: https://github.com/EpicGames/UnrealEngine/pull/9182

**Comment by slonopotamus** [comment] 2022-05-12 13:04
So, I think we shouldn't do anything on ue4-docker side here. Closing?

**Comment by TBBle** [comment] 2022-05-12 14:43
The only thing we could do here is patch-out the change in the source since that [reported worked](https://github.com/adamrehn/ue4-docker/issues/250#issuecomment-1119595247), but I'd like to see what Epic says first, particularly if it turns out this change has propagated into how they build third-party libraries too (that aren't used by the Editor unless the plugin is enabled), for example, so we can see the scope of any possible patch.

I'm ambivalent to whether that means "leave open with await-upstream label" or "close and re-open depending on upstream action".

**Comment by TBBle** [comment] 2022-05-12 16:07
I don't think we would ever want to patch _every_ bug, but there is history of patching build-system bugs in ue4-docker, and "delete a line" is well within the scope of other patches.

That said, this isn't a global build-breaking bug so it probably makes more sense for users whose min-spec target includes non-SSSE3 Linux boxes to maintain that in a fork, or if Epic agree and fix this, upgrade to a version with the fix.

We are after all talking about an instruction set that has been in Intel's CPU range for 15 years, and AMD CPUs for 10 years, as far as I can parse Wikipedia. The [Steam Hardware Survey](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam) lists SSSE3 as supported by 99.38% of the cohort, so given that Epic apparently haven't had the need to revert this in their playerbase in the last 18 months, I don't feel a strong need to patch around it ue4-docker, particularly if it turns out to be sacrificing performance for the vast majority of users, although the code comment doesn't touch upon this as being a motivation.

**Comment by slonopotamus** [comment] 2023-02-06 09:29
See https://github.com/EpicGames/UnrealEngine/commit/0d3889b2e0a41b9628054f861bc31e9f074e6b61. Epics dropped everything older than Bulldozer for AMD and Nehalem for Intel. I don't think we want to fight againts that on ue4-docker side.

**Closed by slonopotamus** 2023-02-06 09:29 UTC
Labels: question, awaiting-upstream
