### ISSUE TITLE
ue4-docker build 4.24 UnrealEngine error

### ISSUE THREAD

**Issue by yangyueren** [adamrehn/ue4-docker#101] opened 2020-10-12 15:30 UTC
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.71 (latest available version is 0.0.71)
Operating system:           Linux (Ubuntu 16.04.7 LTS, 4.15.0-45-generic)
Docker daemon version:      19.03.13
NVIDIA Docker supported:    Yes
Maximum image size:         No limit detected
Available disk space:       155.05 GiB
Total system memory:        220.28 GiB physical, 14.9 GiB virtual
Number of processors:       10 physical, 40 logical
```

ue4-docker build --cuda=9.2 --pull-prerequisites  --exclude=debug --exclude=templates 4.24.3

ERROR: GetBuildPlatform: No BuildPlatform found for Linux
The command '/bin/sh -c ./Engine/Build/BatchFiles/Linux/Build.sh UE4Editor Linux Development -WaitMutex && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''' returned a non-zero code: 5
[ue4-docker build] Error: failed to build image "adamrehn/ue4-engine:4.24.3-cudagl9.2".

**Comment by TBBle** [comment] 2020-11-07 16:17
> ERROR: GetBuildPlatform: No BuildPlatform found for Linux

suggests the necessary toolchain was not found. There might have been more information earlier in the log output, perhaps.

One thing I'd suggest is try it without `--pull-prerequisites` and add `--rebuild`, to confirm that the problem is not something specific to the published [adamrehn/ue4-build-prerequisites:cudagl9.2](https://hub.docker.com/r/adamrehn/ue4-build-prerequisites/tags) image on Docker Hub.

**Comment by adamrehn** [comment] 2020-12-11 08:21
@yangyueren I second what @TBBle suggested, can you please run the build again with the `--pull-prerequisites` flag removed and the `--rebuild` flag added, and post the complete log output?

**Comment by slonopotamus** [comment] 2021-05-18 20:44
No feedback in half a year. Closing.

**Closed by slonopotamus** 2021-05-18 20:44 UTC
Labels: question
