### ISSUE TITLE
Server certificate validation fails while building

### ISSUE THREAD

**Issue by max-lennon** [adamrehn/ue4-docker#262] opened 2022-06-02 15:25 UTC
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.98
Operating system:           Linux (Ubuntu 18.04.6 LTS, 4.15.0-180-generic)
Docker daemon version:      20.10.16
NVIDIA Docker supported:    No
Maximum image size:         No limit detected
Available disk space:       103.76 GiB
Total system memory:        31.31 GiB physical, 59.6 GiB virtual
CPU:                        6 physical, 12 logical (x86_64)

```

Additional details:

- Are you accessing the network through a proxy server? **Yes**

Here's the output when I run ue4-docker build 5.0.2 --no-engine --no-minimal:

```
[ue4-docker build] Using deprecated `--no-*` target specifiers; recommend changing to `--target`
[ue4-docker build] COMMAND-LINE INVOCATION:
[ue4-docker build] ['ue4-docker', '5.0.2', '--no-engine', '--no-minimal']

[ue4-docker build] UNREAL ENGINE VERSION SETTINGS:
[ue4-docker build] Custom build:  No
[ue4-docker build] Release:       5.0.2
[ue4-docker build] Repository:    https://github.com/EpicGames/UnrealEngine.git
[ue4-docker build] Branch/tag:    5.0.2-release

[ue4-docker build] ADVANCED CONFIGURATION OPTIONS:
[ue4-docker build] buildgraph_args: "-set:HostPlatformOnly=true"
[ue4-docker build] excluded_components: {"ddc": false, "debug": false, "templates": false}

[ue4-docker build] LINUX CONTAINER SETTINGS
[ue4-docker build] Base OS image: nvidia/opengl:1.0-glvnd-devel-ubuntu18.04

[ue4-docker build] GENERAL SETTINGS
[ue4-docker build] Build targets: build-prerequisites source
[ue4-docker build] Changelist override: (None specified)
[ue4-docker build] Not excluding any Engine components.

Retrieving the Git credentials that will be used to clone the UE4 repo
Username: maxlennon7@gmail.com
Password: 


[ue4-docker build] Image "adamrehn/ue4-build-prerequisites:opengl-ubuntu18.04" exists and rebuild not requested, skipping build.

[ue4-docker build] Building image "adamrehn/ue4-source:5.0.2-opengl-ubuntu18.04"...
[+] Building 2.1s (8/17)                                                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                                                          0.1s
 => => transferring dockerfile: 4.35kB                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                             0.1s
 => => transferring context: 53B                                                                                                                                              0.0s
 => [internal] load metadata for docker.io/adamrehn/ue4-build-prerequisites:opengl-ubuntu18.04                                                                                0.0s
 => [internal] load build context                                                                                                                                             0.1s
 => => transferring context: 4.54kB                                                                                                                                           0.0s
 => [ 1/13] FROM docker.io/adamrehn/ue4-build-prerequisites:opengl-ubuntu18.04                                                                                                0.0s
 => CACHED [ 2/13] COPY --chown=ue4:ue4 git-credential-helper-endpoint.sh /tmp/git-credential-helper-endpoint.sh                                                              0.0s
 => [ 3/13] RUN chmod +x /tmp/git-credential-helper-endpoint.sh && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'N  0.7s
 => ERROR [ 4/13] RUN mkdir /home/ue4/UnrealEngine &&  cd /home/ue4/UnrealEngine &&  git init &&  git remote add origin "https://github.com/EpicGames/UnrealEngine.git" &&    1.1s
------                                                                                                                                                                             
 > [ 4/13] RUN mkdir /home/ue4/UnrealEngine &&  cd /home/ue4/UnrealEngine &&    git init &&     git remote add origin "https://github.com/EpicGames/UnrealEngine.git" &&        git fetch --progress --depth 1 origin "5.0.2-release" &&   git checkout FETCH_HEAD && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo '':
#8 0.732 Initialized empty Git repository in /home/ue4/UnrealEngine/.git/
#8 0.893 fatal: unable to access 'https://github.com/EpicGames/UnrealEngine.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
------
executor failed running [/bin/sh -c mkdir /home/ue4/UnrealEngine && 	cd /home/ue4/UnrealEngine && 	git init && 	git remote add origin "$GIT_REPO" && 	git fetch --progress --depth 1 origin "$GIT_BRANCH" && 	git checkout FETCH_HEAD && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo '']: exit code: 128
[ue4-docker build] Error: failed to build image "adamrehn/ue4-source:5.0.2-opengl-ubuntu18.04".
```

Notably, the command it seems to be stuck on is ' git remote add origin "https://github.com/EpicGames/UnrealEngine.git" ', while I can run that command manually in a different directory without errors.

**Comment by slonopotamus** [comment] 2022-06-02 15:51
I believe git inside Docker container doesn't trust your proxy. You can workaround this by passing `--opt 'git-config={"http.sslverify": "false"}'`.

**Comment by max-lennon** [comment] 2022-06-02 19:22
Thanks for the advice! This seems to get past the previous failure point, but I now encounter a "GnuTLS recv error (-110): The TLS connection was non-properly terminated." Do you think this is caused by the fix you mentioned?

**Comment by TBBle** [comment] 2022-06-03 10:59
We've seen other GnuTLS errors when running via a proxy or under WSL2, e.g., https://github.com/adamrehn/ue4-docker/issues/203#issuecomment-917529670. This won't have been caused by the change above (that just tells git to not check the certificate), but given both that issue and then the second one, I suspect your proxy is having problems with the git protocol and large files.

Have you tried cloning the UE git repo from where you're running ue4-docker? I expect that will fail the same way, so you'll need to get that working first.

Alternatively, can you run without the network proxy? Proxies that intercept https like that show up quite often as problems for large binary-protocol transfers like this.

**Comment by slonopotamus** [comment] 2022-09-20 19:43
3+ months without any feedback. Sound like it's time to close this. But feel free to comment anyway.

**Closed by slonopotamus** 2022-09-20 19:43 UTC
Labels: question
