### ISSUE TITLE
Build error for `4.25.3` on Linux

### ISSUE THREAD

**Issue by smamessier** [adamrehn/ue4-docker#94] opened 2020-08-18 09:57 UTC
So I have a build error for `4.25.3` on Linux
```
ERROR: Cannot use an old toolchain (missing ToolchainVersion.txt file, assuming version earlier than v11)
``` 

This post helped me solve it: 
https://forums.unrealengine.com/development-discussion/engine-source-github/1687144-missing-toolchainversion-txt-linux-ubuntu-19-04

On Linux it complains on a missing txt file with the toolchain version. Adding it at the end of  `ue4-source`'s Dockerfile fixed the problem:

```
RUN echo "v16_clang-9.0.1-centos7" > /home/ue4/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v16_clang-9.0.1-centos7/ToolchainVersion.txt
```

I could create a PR but you may think of a specific way to fix it?

**Comment by adamrehn** [comment] 2020-08-24 09:19
Apologies for the delay in responding to this issue, I've been inordinately busy over the past couple of months and I'm only now making my way through my GitHub backlog.

Thanks for reporting this, I'll attempt to reproduce the error and determine the most appropriate solution.

**Comment by adamrehn** [comment] 2020-08-25 08:14
@smamessier I've been unable to reproduce the error you encountered. When I build the images for Unreal Engine 4.25.3 the clang toolchain is downloaded and extracted correctly, and the Engine builds successfully. The file you were missing is listed near the end of the log output when `Setup.sh` extracts the toolchain archive in the [ue4-source](https://docs.adamrehn.com/ue4-docker/building-images/available-container-images#ue4-source) image:

```
v16_clang-9.0.1-centos7/ToolchainVersion.txt

Target arch set to: x86_64-unknown-linux-gnu
Building ThirdParty libraries
```

My guess is that either your download of the toolchain archive was corrupted (which I've seen reported happening before outside of containers), or that there was a problem with the toolchain archive file on Epic's CDN that they subsequently corrected. Could you please do the following:

- Revert your Dockerfile changes by installing a fresh version of ue4-docker (e.g. `sudo pip3 install -U ue4-docker`)
- Untag your ue4-source image
- Clean the Docker filesystem layer cache by running [docker system prune](https://docs.docker.com/engine/reference/commandline/system_prune/)
- Re-run your build
- Let me know if it succeeds?

**Comment by tanzle-aames** [comment] 2020-09-24 20:53
@adamrehn I experienced this same error with 4.25.1 several months ago (that I had mentioned to you privately). I never created the Issue.

I just applied the workaround steps you mentioned above and my issue has been resolved.

With 4.25.3, I also am not having the "toolchain" issue.

So, I suspect it is due to a temporary issue with Epic's CDN that they have since resolved.

**Comment by adamrehn** [comment] 2020-12-11 04:21
I've added a note to the troubleshooting section of the ue4-docker documentation covering this problem and the associated fix: <https://docs.adamrehn.com/ue4-docker/building-images/troubleshooting-build-issues#building-the-engine-in-a-linux-container-fails-with-an-error-indicating-that-the-file-toolchainversiontxt-is-missing>

I'm going to close this issue, since the problem is external to ue4-docker itself and there's nothing we can really do to fix issues with the Epic CDN when they do occur.

**Closed by adamrehn** 2020-12-11 04:21 UTC
