### ISSUE TITLE
Error building 4.25.3 on windows server 2019

### ISSUE THREAD

**Issue by Bdoom** [adamrehn/ue4-docker#96] opened 2020-08-31 15:37 UTC
[UE4-Docker Errors.txt](https://github.com/adamrehn/ue4-docker/files/5151211/UE4-Docker.Errors.txt)

The full process is described in the text document attached.

**Comment by Bdoom** [comment] 2020-08-31 15:38
http://download.microsoft.com/download/6/A/2/6A2ECE81-C934-4E47-91CC-52DA00A65345/Installers/e8bc712abeffd7c9711ee3f55d4aa99b.cab



```
windbg v10.0.10586.15 [Approved] - Likely broken for FOSS users (due to download location changes)
windbg package files install completed. Performing other installation steps.
Attempt to get headers for http://download.microsoft.com/download/6/A/2/6A2ECE81-C934-4E47-91CC-52DA00A65345/Installers/e8bc712abeffd7c9711ee3f55d4aa99b.cab failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://download.microsoft.com/download/6/A/2/6A2ECE81-C934-4E47-91CC-52DA00A65345/Installers/e8bc712abeffd7c9711ee3f55d4aa99b.cab'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading windbg
  from 'http://download.microsoft.com/download/6/A/2/6A2ECE81-C934-4E47-91CC-52DA00A65345/Installers/e8bc712abeffd7c9711ee3f55d4aa99b.cab'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://download.microsoft.com/download/6/A/2/6A2ECE81-C934-4E47-91CC-52DA00A65345/Installers/e8bc712abeffd7c9711ee3f55d4aa99b.cab'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
This package is likely not broken for licensed users - see https://chocolatey.org/docs/features-private-cdn.
The install of windbg was NOT successful.
```

This is the issue...

**Comment by Bdoom** [comment] 2020-08-31 15:48
Patch on #92 fixes that issue, but now it hangs on this:
![image](https://user-images.githubusercontent.com/1284431/91739449-e98e1c00-eb7f-11ea-81c7-97328bb8e269.png)

**Comment by Bdoom** [comment] 2020-08-31 15:53
Looks like it's the problem is somewhere in the curl command: https://github.com/adamrehn/ue4-docker/blob/ff1faef1036a71beeef9fd8ee41676224dd6aa09/ue4docker/dockerfiles/ue4-build-prerequisites/windows/install-prerequisites.bat

**Comment by Bdoom** [comment] 2020-08-31 15:58
```@rem Install the Visual Studio 2017 Build Tools workloads and components we need, excluding components with known issues in containers
@rem (Note that we use the Visual Studio 2019 installer here because the old installer now breaks, but explicitly install the VS2017 Build Tools)
curl --progress -L "https://aka.ms/vs/16/release/vs_buildtools.exe" --output %TEMP%\vs_buildtools.exe || goto :error
%TEMP%\vs_buildtools.exe --verbose --quiet --wait --norestart --nocache ^
	--installPath C:\BuildTools ^
	--channelUri "https://aka.ms/vs/15/release/channel" ^
	--installChannelUri "https://aka.ms/vs/15/release/channel" ^
	--channelId VisualStudio.15.Release ^
	--productId Microsoft.VisualStudio.Product.BuildTools ^
	--add Microsoft.VisualStudio.Workload.VCTools;includeRecommended ^
	--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools;includeRecommended ^
	--add Microsoft.VisualStudio.Workload.UniversalBuildTools ^
	--add Microsoft.VisualStudio.Workload.NetCoreBuildTools ^
	--add Microsoft.VisualStudio.Workload.MSBuildTools ^
	--add Microsoft.VisualStudio.Component.NuGet
python C:\buildtools-exitcode.py %ERRORLEVEL% || goto :error```

Added verbose logging, not much helpful

````C:\>curl --progress -L "https://aka.ms/vs/16/release/vs_buildtools.exe" --output C:\Users\ContainerAdministrator\AppData\Local\Temp\vs_buildtools.exe   || goto :error
######################################################################## 100.0%

C:\>C:\Users\ContainerAdministrator\AppData\Local\Temp\vs_buildtools.exe --verbose --quiet --wait --norestart --nocache         --installPath C:\BuildTools     --channelUri "https://aka.ms/vs/15/release/channel"     --installChannelUri "https://aka.ms/vs/15/release/channel"     --channelId VisualStudio.15.Release     --productId Microsoft.VisualStudio.Product.BuildTools   --add Microsoft.VisualStudio.Workload.VCTools;includeRecommended        --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools;includeRecommended       --add Microsoft.VisualStudio.Workload.UniversalBuildTools      --add Microsoft.VisualStudio.Workload.NetCoreBuildTools         --add Microsoft.VisualStudio.Workload.MSBuildTools      --add Microsoft.VisualStudio.Component.NuGet
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\1028\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\2052\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\1042\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\1029\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\1036\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\3082\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\1040\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\1031\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\1041\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\1055\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\1046\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\1045\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\1049\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\HelpFile\1033\help.html...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\vs_setup_bootstrapper.exe...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\Microsoft.Diagnostics.Tracing.EventSource.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\Microsoft.VisualStudio.RemoteControl.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\Microsoft.VisualStudio.Setup.Common.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\Microsoft.VisualStudio.Setup.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\Microsoft.VisualStudio.Setup.Download.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\Microsoft.VisualStudio.Telemetry.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\Microsoft.VisualStudio.Utilities.Internal.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\Newtonsoft.Json.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\tr\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\zh-Hans\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\es\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\it\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\pt-BR\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\ru\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\fr\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\ja\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\cs\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\de\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\ko\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\zh-Hant\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\pl\vs_setup_bootstrapper.resources.dll...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\vs_setup_bootstrapper.config...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\vs_setup_bootstrapper.exe.config...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\detection.json...
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\6eb10c45e5a90c62b52a1786b074a8\vs_bootstrapper_d15\vs_setup_bootstrapper.json...

C:\>python C:\buildtools-exitcode.py 1   || goto :error
The command 'cmd /S /C C:\install-prerequisites.bat && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.' returned a non-zero code: 1
[ue4-docker build] Error: failed to build image "adamrehn/ue4-build-prerequisites:ltsc2019".```

**Comment by Bdoom** [comment] 2020-08-31 23:18
![image](https://user-images.githubusercontent.com/1284431/91777767-b7e87580-ebbe-11ea-8dff-09fff15cf7f5.png)

Does this seem normal for it to be sitting on this for an hour?

**Comment by TBBle** [comment] 2020-11-07 16:07
#92 has now been fixed in ue4-docker 0.0.72.

The hangs seems odd. You can use `docker top <containerID>` to see what's actually chewing up CPU or memory inside the container.

**Comment by adamrehn** [comment] 2020-12-11 08:37
@Bdoom the ["hang"](https://github.com/adamrehn/ue4-docker/issues/96#issuecomment-683863597) with partial output during the installation of the Visual Studio Build Tools is normal, that's just a bug in Microsoft's installer where it seems to buffer the output and doesn't flush it until further into the installation process.

That [hang during compilation](https://github.com/adamrehn/ue4-docker/issues/96#issuecomment-684092081) isn't normal though. In addition to the [docker top](https://docs.docker.com/engine/reference/commandline/top/) command recommended by @TBBle, it might be worth running the build with the the `--monitor` flag to [enable resource monitoring](https://docs.adamrehn.com/ue4-docker/building-images/advanced-build-options#enabling-system-resource-monitoring-during-builds) and see what your host system's CPU/memory usage and available disk space look like during the hang. (If you're running a version of Windows Server with the [Desktop Experience](https://docs.microsoft.com/en-us/windows-server/get-started/getting-started-with-server-with-desktop-experience) installed then you can of course use Windows Explorer and Task Manager to keep an eye on resource usage levels.)

**Comment by slonopotamus** [comment] 2021-05-18 19:51
1. windbg issue was fixed
2. "Hang" during VS Build Tools installation is not a hang, it just needs to download and install lots of things (and @Bdoom passed this point in build process)
3. "Hang" during compilation might be caused by usage of HyperV isolation. Please, avoid that at all costs and use process isolation instead.
4. No feedback for half a year

Resolution: closing

**Closed by slonopotamus** 2021-05-18 19:51 UTC
Labels: bug
